Repository apollographql/space-kit, pull requests merged in 2019-08, with the labels that each got.

#48 Set up automatic npm releases using `auto`
  .autorc
  .circleci/config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/release.sh
Labels: major

#50 Make release.sh executable
  scripts/release.sh
Labels: internal, patch

#51 Add name and email to `auto` config
  .autorc
Labels: patch

#52 Fix modals sizes in Safari
  src/Modal/Modal.tsx
Labels: patch

#54 Add workflow to re-run the `check-label` CircleCI job when labels are changed
  .github/main.workflow
  README.md
Labels: skip-release

#53 Speed up `check-labels` task by not installing dependencies
  .circleci/config.yml
Labels: patch

#55 Fix release script
  package-lock.json
  package.json
Labels: patch

#56 Test automatic releases
  scripts/release.sh
Labels: patch

#57 Refactor icon generation
  .eslintignore
  .gitignore
  icons/tsconfig.json
  package-lock.json
  package.json
  src/Button/Button.story.tsx
  src/icons/Icons.story.jsx
  src/icons/scripts/convert.ts
  tsconfig.build.json
  tsconfig.json
Labels: patch

#58 remove default size on icons
  src/icons/scripts/convert.ts
Labels: patch

#59 Change `Icon` to have `thin` and `normal` weights
  src/icons/Icons.story.jsx
  src/icons/scripts/convert.ts
Labels: patch

#60 Fix `npm watch` script
  package.json
Labels: skip-release

#61 fix `watch:typescript` script
  package.json
Labels: skip-release

#46 AP-700 Export `emotionCacheProviderFactory` so allow consumers to override classes
  .gitignore
  README.md
  package-lock.json
  package.json
  src/emotionCacheProviderFactory/index.tsx
Labels: minor

#63 fix(button): center icons
  src/Button/Button.tsx
Labels: patch

#62 install emotion dependencies in dependencies
  package-lock.json
  package.json
Labels: patch

#64 Automatically calculate button text color
  package-lock.json
  package.json
  src/Button/Button.story.tsx
  src/Button/Button.tsx
Labels: minor

#65 feat(button): Replace feel="secondary" with color={colors.white}
  src/Button/Button.story.tsx
  src/Button/Button.tsx
  src/Modal/Modal.story.tsx
Labels: minor

#66 Table Margin Fix
  src/Table/Table.tsx
Labels: patch

#45 AP-544 Implement Text Inputs
  .gitignore
  .storybook/webpack.config.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/Card/Card.tsx
  src/TextField/TextField.story.tsx
  src/TextField/TextField.tsx
  src/TextField/index.ts
  src/icons/svgs/solids/icon-alert-solid-sl.svg
  src/shared/DemoSection.tsx
Labels: minor

#67 Small text field fixes
  src/TextField/TextField.tsx
Labels: minor

#69 Correct npm script for cleaning TextField, make labels optional
  package.json
Labels: patch

#71 update SSH fingerprint to use apollo-bot2 instead of justinanastos
  .circleci/config.yml
Labels: skip-release

#74 build: update ssh fingerprint to release through `apollo-bot2`
  .circleci/config.yml
Labels: skip-release

#70 Add `as` prop to `Button`
  package-lock.json
  package.json
  src/Button/Button.story.tsx
  src/Button/Button.tsx
  src/shared/ComponentWithAs.ts
Labels: minor

#72 Add `inputAs` prop to `TextField` to customize how the underlying `input` is rendered
  src/TextField/TextField.story.tsx
  src/TextField/TextField.tsx
Labels: minor

#77 feat(Button): change light theme button shadow per @torres
  src/Button/Button.tsx
Labels: patch

#76 fix(TextField): Pass `name` and `type` to `<input>`
  src/TextField/TextField.tsx
Labels: patch

#75 Add loading spinner
  README.md
  src/Button/Button.story.tsx
  src/Loaders/Loaders.story.tsx
  src/Loaders/LoadingSpinner.tsx
  src/Loaders/index.ts
  src/TextField/TextField.story.tsx
  src/shared/DemoSection.tsx
Labels: minor

#80 Change `Button` `as` prop to only accept `React.ReactElement`
  src/Button/Button.story.tsx
  src/Button/Button.tsx
Labels: major

#78 medium modals should have 32 px above actions
  src/Modal/Modal.tsx
Labels: patch

#87 Remove font weight from smaller fonts
  src/typography/TypographyDefinition.ts
  src/typography/base.ts
Labels: minor

#89 AP-783 set modal `max-height` to 60%
  src/Modal/Modal.tsx
Labels: patch
