Repository apollographql/space-kit, pull requests merged in 2019-11, with the labels that each got.

#132 AP-1099 Set default size of icons to be 20px by 20px
  src/icons/Icons.story.jsx
  src/icons/scripts/convert.ts
Labels: minor

#133 Improve `TextField` tests
  package-lock.json
  package.json
  src/TextField/TextField.spec.tsx
Labels: 🏗 internal

#134 AP-1099 Remove default width on icons
  .autorc
  src/icons/Icons.story.jsx
  src/icons/scripts/convert.ts
Labels: bug fix

#136 AP-1165 Disable label checks for PRs
  .circleci/config.yml
  .github/actions/run-circle-ci-job/README.md
  .github/actions/run-circle-ci-job/action.yml
  .github/actions/run-circle-ci-job/dist/index.js
  .github/actions/run-circle-ci-job/index.js
  .github/workflows/issue_comment.yml
  .github/workflows/pr-check-label.yml
Labels: internal

#138 Stop CI trying to run `check-label`
  .circleci/config.yml
Labels: 🏗 internal

#139 remove unnecessary scrollbar
  src/Modal/Modal.tsx
Labels: bug fix

#131 AP-786 ✨ add illustrations
  .gitignore
  package.json
  src/icons/scripts/convert.ts
  src/illustrations/LICENSE.md
  src/illustrations/scripts/.eslintrc.json
  src/illustrations/scripts/convert.ts
  src/illustrations/scripts/convertUtils/setupSvgo.ts
  src/illustrations/scripts/formatComponentName.ts
  src/illustrations/svgs/asteroid.svg
  src/illustrations/svgs/astronaut1.svg
  src/illustrations/svgs/astronaut2.svg
  src/illustrations/svgs/moon.svg
  src/illustrations/svgs/observatory.svg
  src/illustrations/svgs/planet.svg
  src/illustrations/svgs/rocket1.svg
  src/illustrations/svgs/rocket2.svg
  src/illustrations/svgs/satellite1.svg
  src/illustrations/svgs/satellite2.svg
  src/illustrations/svgs/telescope.svg
Labels: minor

#137 AP-1075 Fix spinner remounting restarts
  src/Loaders/LoadingSpinner.tsx
  typings/storybook-chromatic__isChromatic/index.d.ts
Labels: minor

#140 Change loader spin duration to 750ms
  src/Loaders/LoadingSpinner.tsx
Labels: minor

#143 Stop stripping comments from TypeScript builds
  tsconfig.build.json
  tsconfig.json
Labels: 🏗 internal

#142 AP-1222 Add option to disable Modal animations
  .gitignore
  .storybook/config.js
  package-lock.json
  package.json
  src/Modal/Modal.tsx
  src/SpaceKitProvider/SpaceKitProvider.spec.tsx
  src/SpaceKitProvider/SpaceKitProvider.story.mdx
  src/SpaceKitProvider/index.tsx
Labels: minor

#141 Turn off syncAnimationRestarts for chromatic and buttons
  src/Loaders/LoadingSpinner.tsx
Labels: minor

#145 Fix: avoid descriptions pushing actions off-screen - AP-1138
  src/Card/Card.story.tsx
  src/Card/Card.tsx
Labels: minor
