Repository apollographql/space-kit, pull requests merged in 2019-09, with the labels that each got.

#81 AP-714 Use storybook docs
  .eslintrc.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/presets.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/Button/Button.stories.mdx
  src/Button/Button.story.tsx
  src/Button/button.stories/ButtonLayout.tsx
  src/Card/Card.story.tsx
  src/Loaders/Loaders.story.tsx
  src/Modal/Modal.story.tsx
  src/Table/Table.stories.mdx
  src/Table/Table.story.tsx
  src/Table/Table.tsx
  src/Table/table.stories/alice-howell.png
  src/Table/table.stories/benjamin-lawrence.png
  src/Table/table.stories/cynthia-bowman.png
  src/Table/table.stories/jeremy-griffin.png
  src/Table/table.stories/jeremy-jacobs.png
  src/TextField/TextField.stories.mdx
  src/TextField/TextField.story.tsx
  src/colors/utils/getOffsetInPalette.ts
  src/icons/Icons.story.jsx
Labels: skip-release

#90 AP-714 Move emotion export docs to storybook
  README.md
  src/emotionCacheProviderFactory/emotionCacheProviderFactory.stories.mdx
Labels: skip-release

#34 AP-703: Write integration tests (AP-780)
  .circleci/config.yml
  .gitignore
  README.md
  __mocks__/fileMock.js
  jest.config.js
  package-lock.json
  package.json
  src/Button/Button.spec.tsx
  src/Button/Button.tsx
  src/Modal/Modal.spec.tsx
  src/Modal/Modal.tsx
  src/Table/Table.spec.tsx
  src/Table/Table.tsx
  src/colors/utils/findPaletteByColor.spec.ts
  src/colors/utils/getOffsetInPalette.spec.ts
  src/colors/utils/getOffsetInPalette.ts
  src/emotionCacheProviderFactory/emotionCacheProviderFactory.spec.tsx
Labels: minor

#92 AP-809 Add loading state to button
  src/Button/Button.stories.mdx
  src/Button/Button.tsx
  src/Loaders/Loaders.story.tsx
  src/Loaders/LoadingSpinner.stories.mdx
  src/Loaders/LoadingSpinner.tsx
  src/Modal/Modal.tsx
Labels: minor

#95 AP-808: passthrough `autoFocus` prop to underlying `input` in `TextField`
  src/TextField/TextField.spec.tsx
  src/TextField/TextField.tsx
Labels: minor

#93 AP-808 Add `will-change` to `LoadingSpinner`'s animation
  src/Loaders/LoadingSpinner.tsx
Labels: patch

#96 AP-808 Add `as` prop to `Modal`
  src/Modal/Modal.tsx
Labels: minor

#97 AP-801 Show appropriate cursor for `Button`'s `loading` and `disabled` states
  src/Button/Button.spec.tsx
  src/Button/Button.tsx
Labels: patch

#99 Add Chromatic visual testing
  .circleci/config.yml
  .storybook/config.js
  package-lock.json
  package.json
Labels: skip-release

#98 Document `Button as={}`
  package-lock.json
  package.json
  src/Button/Button.stories.mdx
Labels: skip-release

#104 Add the layout-module icon
  src/icons/svgs/essentials/icon-layout-module.svg
Labels: minor

#106 AP-829 converted main.workflow to Actions V2 yml files
  .eslintignore
  .gitattributes
  .github/actions/run-circle-ci-job/README.md
  .github/actions/run-circle-ci-job/action.yml
  .github/actions/run-circle-ci-job/dist/index.js
  .github/actions/run-circle-ci-job/index.js
  .github/main.workflow
  .github/workflows/issue_comment.yml
  .github/workflows/pr-check-label.yml
  decoy.js
  package-lock.json
  package.json
Labels: skip-release

#105 AP-704 Setup and configure renovate
  .autorc
  package-lock.json
  package.json
  renovate.json
Labels: skip-release

#119 Remove renovate
  package.json
  renovate.json
Labels: skip-release

#120 Increase modal max height and center contents
  src/Modal/Modal.tsx
Labels: minor

#121 Add copy icon
  src/icons/svgs/controls/icon-copy-sl.svg
Labels: minor
