Repository apollographql/space-kit, pull requests merged in 2019-10, with the labels that each got.

#123 Upgrade storybook to production v5.2.1
  package-lock.json
  package.json
Labels: skip-release

#124 Update auto to add Jira links
  .autorc
  package-lock.json
  package.json
Labels: skip-release

#125 AP-1011 Stop wrapping long text in Buttons
  src/Button/Button.stories.mdx
  src/Button/Button.tsx
Labels: minor

#122 AP-919 Stop propagation of clicks when disabled using input as
  src/Button/Button.spec.tsx
  src/Button/Button.tsx
Labels: minor

#127 Fix changelog configuration for adding jira links
  .autorc
Labels: skip-release

#126 Add framer-motion as peer-dep; animate modal AP-812
  package-lock.json
  package.json
  src/Modal/Modal.tsx
Labels: minor

#128 AP-1071 Write docs on how to use `npm link` with consuming libraries
  .autorc
  README.md
Labels: 📚 documentation

#129 📚 improve documentation for `as` prop in `Button`
  src/Button/Button.stories.mdx
Labels: 📚 documentation
