Repository apollographql/space-kit, pull requests merged in 2019-12, with the labels that each got.

#147 Make tslib a proper dep
  package-lock.json
  package.json
Labels: bug fix

#149 AP-1023 Use rollup to bundle library
  .gitignore
  .npmignore
  .vscode/settings.json
  package-lock.json
  package.json
  rollup.config.js
  tsconfig.build.json
Labels: 🏗 internal

#151 feat(LoadingSpinner): Add `progressbar` role
  src/Loaders/LoadingSpinner.spec.tsx
  src/Loaders/LoadingSpinner.tsx
Labels: minor
