Repository apollographql/space-kit, pull requests merged in 2020-10, with the labels that each got.

#241 Add headset icon
  src/icons/svgs/essentials/icon-headset.svg
Labels: minor

#245 Update tippy, react, jest, and testing dependencies
  package-lock.json
  package.json
  src/Button/Button.tsx
  src/ListItem/index.tsx
  src/Loaders/LoadingSpinner.tsx
  src/Modal/Modal.tsx
  src/Popover/popover/sizeModifier.ts
  src/fonts/fonts.ts
  src/typography/Typography.story.tsx
  src/typography/TypographyDefinition.ts
Labels: dependencies

#244 Show focus on `Button` when interacting with keyboard
  package-lock.json
  package.json
  rollup.config.js
  src/Button/Button.spec.tsx
  src/Button/Button.stories.mdx
  src/Button/Button.tsx
  src/Button/button/ButtonIcon.tsx
Labels: minor

#247 AR-1672, AR-1909 Add `tr` and column-level `th`/`td` customization to `Table`
  jest.config.js
  src/Table/Table.spec.tsx
  src/Table/Table.stories.mdx
  src/Table/Table.tsx
Labels: minor

#248 Stop checking TypeScript in `rollup` script
  rollup.config.js
Labels: internal

#243 Create `Select` component
  .eslintrc.js
  .gitignore
  jest/setup.js
  package-lock.json
  package.json
  rollup.config.js
  src/AbstractTooltip/abstractTooltip/matchTriggerWidth.ts
  src/AbstractTooltip/index.tsx
  src/Button/Button.tsx
  src/List/List.spec.tsx
  src/List/index.tsx
  src/ListConfig/index.tsx
  src/ListDivider/index.tsx
  src/ListItem/ListItem.spec.tsx
  src/ListItem/index.tsx
  src/Popover/PopoverTests.story.tsx
  src/Popover/index.tsx
  src/Select/Select.spec.tsx
  src/Select/Select.story.mdx
  src/Select/SelectTests.story.tsx
  src/Select/index.tsx
  src/Select/select/reactNodeToDownshiftItems.spec.tsx
  src/Select/select/reactNodeToDownshiftItems.ts
  src/TextField/TextField.stories.mdx
  src/TextField/TextField.tsx
Labels: minor

#250 fix icon button spacing
  src/Button/Button.tsx
  src/Select/Select.story.mdx
  src/Select/index.tsx
Labels: bug fix

#249 AR-1917: Icons: use overridable props for `fill` and `stroke`
  README.md
  src/icons/scripts/convert.ts
  src/icons/scripts/createStory.ts
Labels: minor

#252 fix flakey test in `Popover`
  src/Popover/Popover.spec.tsx
Labels: internal

#246 Remove extra top margin for TextField error
  src/TextField/TextField.tsx
Labels: major, skip-release
