Repository apollographql/space-kit, pull requests merged in 2020-12, with the labels that each got.

#280 Add opensource icon
  src/icons/svgs/essentials/icon-opensource.svg
Labels: minor

#279 Fix events fired by `Select`
  package-lock.json
  package.json
  rollup.config.js
  src/Select/Select.spec.tsx
  src/Select/Select.story.mdx
  src/Select/index.tsx
  src/shared/createElementFromAs.ts
Labels: minor

#282 docs(Select): Add a write-up on how to add label props
  src/Select/Select.story.mdx
Labels: documentation

#281 Fix controlled/uncontrolled switch
  src/Select/index.tsx
Labels: minor

#284 Dont warn whenever using controlled version of component
  src/Select/index.tsx
Labels: bug fix

#285 add trailing commas for all transpiled code
  src/.prettierrc.toml
  src/AbstractTooltip/abstractTooltip/matchTriggerWidth.ts
  src/AlertBanner/AlertBanner.spec.tsx
  src/AlertCard/AlertCard.tsx
  src/Button/Button.spec.tsx
  src/Button/Button.tsx
  src/Button/button.stories/ButtonLayout.tsx
  src/Card/Card.spec.tsx
  src/Card/Card.tsx
  src/ConfirmationTooltip/ConfirmationTooltip.spec.tsx
  src/ConfirmationTooltip/ConfirmationTooltip.story.tsx
  src/List/List.spec.tsx
  src/List/index.tsx
  src/ListConfig/index.tsx
  src/ListDivider/index.tsx
  src/ListHeading/index.tsx
  src/ListItem/ListItem.spec.tsx
  src/ListItem/index.tsx
  src/Loaders/LoadingSpinner.spec.tsx
  src/Loaders/LoadingSpinner.tsx
  src/Modal/Modal.spec.tsx
  src/Modal/Modal.story.tsx
  src/Modal/Modal.tsx
  src/Popover/Popover.spec.tsx
  src/Popover/index.tsx
  src/Popover/popover/sizeModifier.ts
  src/Select/Select.spec.tsx
  src/Select/SelectTests.story.tsx
  src/Select/index.tsx
  src/Select/select/reactNodeToDownshiftItems.spec.tsx
  src/Select/select/reactNodeToDownshiftItems.ts
  src/SpaceKitProvider/SpaceKitProvider.spec.tsx
  src/Switch/Switch.spec.tsx
  src/Switch/index.tsx
  src/Switch/switch.story/Wrapper.tsx
  src/Switch/switch/Label.tsx
  src/Table/Table.spec.tsx
  src/Table/Table.tsx
  src/TextField/TextField.spec.tsx
  src/TextField/TextField.tsx
  src/Tooltip/Tooltip.spec.tsx
  src/Tooltip/Tooltip.story.tsx
  src/colors/utils/findPaletteByColor.ts
  src/colors/utils/getOffsetInPalette.spec.ts
  src/colors/utils/getOffsetInPalette.ts
  src/emotionCacheProviderFactory/emotionCacheProviderFactory.spec.tsx
  src/emotionCacheProviderFactory/emotionCacheProviderFactory.stories.mdx
  src/emotionCacheProviderFactory/index.tsx
  src/icons/icons.story/IconDemo.tsx
  src/icons/scripts/assertNoDuplicates.ts
  src/icons/scripts/convert.ts
  src/icons/scripts/createStory.ts
  src/illustrations/Illustrations.spec.tsx
  src/illustrations/scripts/convert.ts
  src/pictograms/pictograms.spec.tsx
  src/pictograms/scripts/convert.ts
  src/shared/ComponentWithAs.ts
  src/shared/DebugTooltip.tsx
  src/shared/cloneElements.tsx
  src/shared/verticalListMarginFromPadding.ts
Labels: internal

#286 Update GitHub icon
  src/icons/svgs/social/icon-github.svg
Labels: minor

#290 Tweak `Select` and sync input heights
  src/Button/Button.tsx
  src/Select/Select.spec.tsx
  src/Select/Select.story.mdx
  src/Select/index.tsx
  src/TextField/TextField.tsx
  src/shared/inputHeightDictionary.ts
Labels: patch

#291 Card: don't apply margin without a header
  src/Card/Card.story.tsx
  src/Card/Card.tsx
Labels: bug fix
