Repository apollographql/space-kit, pull requests merged in 2020-04, with the labels that each got.

#162 Add `containerAs` prop to Modal
  src/Modal/Modal.spec.tsx
  src/Modal/Modal.tsx
Labels: minor

#163 Add run icon
  src/icons/svgs/controls/icon-run-sl.svg
Labels: minor

#164 Add warning and book icons
  src/icons/svgs/essentials/icon-book-sl.svg
  src/icons/svgs/essentials/icon-warning-sl.svg
Labels: minor

#165 Restore CI check to require a label be applied before merging a PR
  .autorc
  .circleci/config.yml
  .github/actions/run-circle-ci-job/README.md
  .github/actions/run-circle-ci-job/action.yml
  .github/actions/run-circle-ci-job/dist/index.js
  .github/actions/run-circle-ci-job/index.js
  .github/workflows/issue_comment.yml
  .github/workflows/pr-check-label.yml
  .storybook/config.js
  .storybook/privatePresets/ignoreTestFilesPreset.js
  build-reset.ts
  package-lock.json
  package.json
  src/ConfirmationTooltip/index.tsx
  src/Menu/Menu.spec.tsx
  src/Menu/index.tsx
  src/MenuConfig/index.tsx
  src/MenuItem/index.tsx
  src/MenuItemClickListener/index.tsx
  src/Table/Table.spec.tsx
  src/colors/utils/findPaletteByColor.ts
  src/colors/utils/getOffsetInPalette.ts
  src/icons/Icons.story.jsx
  src/icons/scripts/convert.ts
  src/illustrations/Illustrations.spec.tsx
  src/illustrations/scripts/convert.ts
  stories/Color.stories.js
Labels: internal

#166 AR-1541 Upgrade underlying dependencies and logic in menus and tooltips
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  rollup.config.js
  src/AbstractTooltip/abstractTooltip/TippyStyles.tsx
  src/AbstractTooltip/index.tsx
  src/ConfirmationTooltip/ConfirmationTooltip.spec.tsx
  src/Menu/Menu.spec.tsx
  src/Menu/Menu.story.mdx
  src/Menu/MenuTests.story.jsx
  src/Menu/index.tsx
  src/Menu/menu/TippyMenuStyles.tsx
  src/Menu/menu/sizeModifier.ts
Labels: major

#169 Fix broken release process
  .autorc
  package-lock.json
  package.json
Labels: internal

#168 adds another operations icon
  src/icons/svgs/navigation/icon-operations-sl.svg
  src/icons/svgs/navigation/icon-operations.svg
Labels: minor

#170 Add success solid icon
  src/icons/svgs/solids/icon-success-solid-sl.svg
Labels: minor
