Repository apollographql/space-kit, pull requests merged in 2020-08, with the labels that each got.

#214 Upgrade storybook to v6
  .storybook/main.js
  .storybook/presets.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/AlertBanner/AlertBanner.story.mdx
  src/AlertCard/AlertCard.story.mdx
  src/Button/Button.stories.mdx
  src/List/List.story.mdx
  src/Loaders/LoadingSpinner.stories.mdx
  src/Modal/Modal.tsx
  src/Popover/Popover.story.mdx
  src/Popover/PopoverTests.story.jsx
  src/SpaceKitProvider/SpaceKitProvider.story.mdx
  src/Table/Table.stories.mdx
  src/TextField/TextField.stories.mdx
  src/Tooltip/TooltipGuide.story.mdx
  src/emotionCacheProviderFactory/emotionCacheProviderFactory.stories.mdx
  src/illustrations/scripts/convert.ts
Labels: patch

#215 Update tests to wrap `act` calls and modernize `Button` tests
  src/Button/Button.spec.tsx
  src/ConfirmationTooltip/ConfirmationTooltip.spec.tsx
  src/Popover/Popover.spec.tsx
  src/TextField/TextField.spec.tsx
Labels: internal

#212 AR-748 Add `Switch` component
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  .storybook/preview/ThemedCanvas.tsx
  package-lock.json
  package.json
  rollup.config.js
  src/SpaceKitProvider/index.tsx
  src/Switch/Switch.spec.tsx
  src/Switch/Switch.story.mdx
  src/Switch/index.tsx
  src/Switch/switch.story/Wrapper.tsx
  src/Switch/switch/Label.tsx
  src/Tooltip/Tooltip.spec.tsx
Labels: minor

#218 Fix Card bottom margin with falsey children
  src/Card/Card.tsx
Labels: minor

#217 AR-1818 Modal: Make `as` prop propogate `ref`
  src/Modal/Modal.spec.tsx
  src/Modal/Modal.tsx
Labels: minor
