Repository apollographql/space-kit, pull requests merged in 2020-09, with the labels that each got.

#220 Add relative to label so VisuallyHidden is inside instead of under it
  src/Switch/index.tsx
Labels: bug fix

#221 Bump version to: 7.11.1
  package.json
Labels: skip-release

#222 Add changelog icon
  src/icons/svgs/essentials/icon-changelog.svg
Labels: minor

#224 adds icon-break to essentials category
  src/icons/svgs/essentials/icon-break.svg
Labels: minor

#226 Try to fix releases
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/release.sh
Labels: patch

#227 Test automatic releases
  .autorc
Labels: patch

#228 Update SSH key to try to fix automatic releases
  .circleci/config.yml
  scripts/release.sh
Labels: patch

#229 WIP: Fixing releases
  scripts/release.sh
Labels: bug fix

#230 Sort types in `AbstractTooltip`
  src/Tooltip/index.tsx
Labels: patch

#231 Add new icons (Clipboard, Codeblock, Sync, Table)
  src/icons/svgs/controls/icon-clipboard.svg
  src/icons/svgs/controls/icon-codeblock.svg
  src/icons/svgs/controls/icon-sync.svg
  src/icons/svgs/controls/icon-table.svg
Labels: minor

#225 Upgrade eslint and TypeScript dependencies
  .circleci/config.yml
  .eslintrc.js
  .storybook/preview.js
  components-util/Color.jsx
  package-lock.json
  package.json
  src/Tooltip/tooltip/mouseRestPlugin.ts
  src/emotionCacheProviderFactory/index.tsx
  src/icons/Icons.story.jsx
  src/shared/ComponentWithAs.ts
  typings/storybook-chromatic__isChromatic/index.d.ts
Labels: patch

#234 AR-1848 Add CI check for icons that will generate the same filename
  .circleci/config.yml
  package.json
  src/icons/scripts/assertNoDuplicates.ts
  src/icons/svgs/essentials/icon-planet-1-sl.svg
  src/icons/svgs/essentials/icon-satellite-1-sl.svg
  src/icons/svgs/essentials/icon-ship-1-sl.svg
  src/icons/svgs/essentials/icon-ship-3-sl.svg
  src/icons/svgs/navigation/icon-document.svg
  src/icons/svgs/navigation/icon-home-sl.svg
  src/icons/svgs/navigation/icon-operations.svg
  src/icons/svgs/navigation/icon-support.svg
Labels: internal

#235 Upgrade `Icon` docspage and storybook stories
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/icons/Icons.story.jsx
  src/icons/icons.story/IconDemo.tsx
  src/icons/scripts/createStory.ts
Labels: documentation

#237 Restore Color storybook story
  .storybook/main.js
Labels: documentation

#238 `AlertBanner`: wrap `children` in customizable `childrenContainerAs` element
  src/AlertBanner/AlertBanner.spec.tsx
  src/AlertBanner/AlertBanner.tsx
Labels: minor

#239 Add Pictograms
  .gitignore
  README.md
  package.json
  rollup.config.js
  src/pictograms/LICENSE.md
  src/pictograms/pictograms.spec.tsx
  src/pictograms/pictograms.story.mdx
  src/pictograms/scripts/.eslintrc.json
  src/pictograms/scripts/convert.ts
  src/pictograms/scripts/convertUtils/setupSvgo.ts
  src/pictograms/scripts/formatComponentName.ts
  src/pictograms/svgs/acorn.svg
  src/pictograms/svgs/camera.svg
  src/pictograms/svgs/client.svg
  src/pictograms/svgs/deliver.svg
  src/pictograms/svgs/develop.svg
  src/pictograms/svgs/flip-flops.svg
  src/pictograms/svgs/gears.svg
  src/pictograms/svgs/observe.svg
  src/pictograms/svgs/rubber-duck.svg
  src/pictograms/svgs/server.svg
  src/pictograms/svgs/tooling.svg
  src/pictograms/svgs/watch.svg
Labels: minor

#240 Sort storybook stories
  .storybook/preview.js
Labels: documentation
