Repository apollographql/space-kit, pull requests merged in 2020-06, with the labels that each got.

#177 Apply hover states to `MenuItem` and `Button` when `aria-expanded="true"`
  src/Button/Button.stories.mdx
  src/Button/Button.tsx
  src/Menu/MenuTests.story.jsx
  src/MenuItem/index.tsx
Labels: minor

#179 AR-1689 Fix crashing chromatic builds
  .circleci/config.yml
  package.json
Labels: internal

#178 Add color configurability to `Menu`
  src/Button/Button.tsx
  src/Menu/Menu.story.mdx
  src/Menu/index.tsx
  src/MenuConfig/index.tsx
  src/MenuItem/index.tsx
  src/colors/colors.ts
  src/colors/utils/findPaletteByColor.ts
  src/colors/utils/getOffsetInPalette.ts
Labels: minor

#181 Add history and left/right/down/up double arrow icons
  src/icons/svgs/controls/icon-double-arrow-down.svg
  src/icons/svgs/controls/icon-double-arrow-left.svg
  src/icons/svgs/controls/icon-double-arrow-right.svg
  src/icons/svgs/controls/icon-double-arrow-up.svg
  src/icons/svgs/essentials/icon-history.svg
Labels: minor

#180 Add Midnight color palette to SpaceKit
  src/colors/colors.ts
  stories/Color.metadata.js
  stories/Color.stories.js
Labels: minor

#183 link npm badge to npm page in readme
  README.md
Labels: internal

#185 Adds keyboard control icon
  src/icons/svgs/controls/icon-keyboard.svg
Labels: minor

#174 AR-572 Create Alert component
  .gitignore
  src/AlertCard/AlertCard.story.mdx
  src/AlertCard/AlertCard.tsx
  src/AlertCard/index.ts
  src/Button/Button.tsx
  src/MenuItem/index.tsx
  src/Modal/Modal.tsx
  src/icons/svgs/solids/icon-error-solid.svg
  src/icons/svgs/solids/icon-info-solid-sl.svg
  src/icons/svgs/solids/icon-success-solid-sl.svg
  src/shared/assertUnreachable.ts
Labels: minor

#182 AP-1658 Create `Popup` and `List` components
  .gitignore
  rollup.config.js
  src/List/List.spec.tsx
  src/List/List.story.mdx
  src/List/index.tsx
  src/ListConfig/index.tsx
  src/ListDivider/index.tsx
  src/ListHeading/index.tsx
  src/ListItem/ListItem.spec.tsx
  src/ListItem/index.tsx
  src/Menu/Menu.spec.tsx
  src/Menu/Menu.story.mdx
  src/MenuConfig/index.tsx
  src/MenuItem/index.tsx
  src/MenuItemClickListener/index.tsx
  src/Popover/Popover.spec.tsx
  src/Popover/Popover.story.mdx
  src/Popover/PopoverTests.story.jsx
  src/Popover/index.tsx
  src/Popover/popover/TippyPopoverStyles.tsx
  src/Popover/popover/sizeModifier.ts
  src/Tooltip/Tooltip.story.tsx
  src/icons/svgs/theme/apollo-logo.svg
  src/shared/cloneElements.tsx
  src/shared/verticalListMarginFromPadding.ts
Labels: major

#186 AR-1658 Fix bug where `className` isn't passed through to `ListItem`
  src/ListItem/ListItem.spec.tsx
  src/ListItem/index.tsx
Labels: bug fix

#171 Add className to Tooltip prop types
  src/Tooltip/index.tsx
Labels: patch

#187 add icons for light/dark toggle
  src/icons/svgs/controls/icon-moon.svg
  src/icons/svgs/controls/icon-sun.svg
Labels: minor

#188 add viewbox to sun/moon icons
  src/icons/svgs/controls/icon-moon.svg
  src/icons/svgs/controls/icon-sun.svg
Labels: patch

#189 ✨ add `placement` prop to `Tooltip`
  src/Tooltip/index.tsx
Labels: patch

#176 AR-1634: Remove focus from Buttons when you mouseout with a mouse button pressed
  src/Button/Button.spec.tsx
  src/Button/Button.tsx
Labels: bug fix

#190 Adds new Explorer icon
  src/icons/svgs/navigation/icon-explorer-sl.svg
  src/icons/svgs/navigation/icon-explorer.svg
Labels: minor

#191 Replace old explorer icon with fields icon
  src/icons/svgs/navigation/icon-fields-sl.svg
Labels: bug fix

#192 Update AlertCard dark theme to use midnight tones
  src/AlertCard/AlertCard.tsx
Labels: minor

#194 ✨ add new Fields icon
  src/icons/svgs/navigation/icon-fields-sl.svg
  src/icons/svgs/navigation/icon-fields.svg
Labels: minor

#195 Adds unavailable icon
  src/icons/svgs/essentials/icon-unavailable.svg
Labels: minor

#196 Update Edit icon
  src/icons/svgs/controls/icon-edit-sl.svg
  src/icons/svgs/controls/icon-edit.svg
Labels: minor

#197 darken spinner trail by 1 shade
  src/Loaders/LoadingSpinner.tsx
Labels: major
