Repository apollographql/space-kit, pull requests merged in 2020-07, with the labels that each got.

#198 Adding new icons to support navigation update
  package-lock.json
  src/icons/svgs/essentials/icon-client.svg
  src/icons/svgs/essentials/icon-deliver.svg
  src/icons/svgs/essentials/icon-develop.svg
  src/icons/svgs/essentials/icon-document.svg
  src/icons/svgs/essentials/icon-home-sl.svg
  src/icons/svgs/essentials/icon-observe.svg
  src/icons/svgs/essentials/icon-operations.svg
  src/icons/svgs/essentials/icon-planet-1-sl.svg
  src/icons/svgs/essentials/icon-satellite-1-sl.svg
  src/icons/svgs/essentials/icon-server.svg
  src/icons/svgs/essentials/icon-ship-1-sl.svg
  src/icons/svgs/essentials/icon-ship-3-sl.svg
  src/icons/svgs/essentials/icon-support.svg
  src/icons/svgs/essentials/icon-tooling.svg
Labels: minor

#200 AR-1681 Create AlertBanner component
  .gitignore
  src/AlertBanner/AlertBanner.story.mdx
  src/AlertBanner/AlertBanner.tsx
  src/AlertBanner/index.ts
  src/AlertCard/AlertCard.tsx
Labels: minor

#201 Remove drop shadow from AlertBanner
  src/AlertBanner/AlertBanner.story.mdx
  src/AlertBanner/AlertBanner.tsx
Labels: patch

#202 Update overflow icon
  src/icons/svgs/solids/icon-overflow-solid-sl.svg
  src/icons/svgs/solids/icon-overflow-solid.svg
Labels: minor

#203 Update share icon
  src/icons/svgs/controls/icon-share-sl.svg
  src/icons/svgs/controls/icon-share.svg
Labels: minor

#204 Popover: add interactive property
  src/Popover/Popover.spec.tsx
  src/Popover/Popover.story.mdx
  src/Popover/index.tsx
Labels: minor

#206 Modal: add verticalScrollMode property to limit overflow to children
  src/Modal/Modal.story.tsx
  src/Modal/Modal.tsx
Labels: minor

#208 Update references to default branch of `main`
  .circleci/config.yml
  README.md
  src/Table/Table.stories.mdx
Labels: bug fix

#209 Add whitespace to readme just to trigger builds
  README.md
Labels: bug fix

#211 AR-1781 Don't render `Tooltip`, `ConfirmationTooltip`, or `Popover` if `content` prop is `undefined`
  src/ConfirmationTooltip/ConfirmationTooltip.story.tsx
  src/ConfirmationTooltip/index.tsx
  src/Popover/PopoverTests.story.jsx
  src/Popover/index.tsx
  src/Tooltip/Tooltip.story.tsx
  src/Tooltip/index.tsx
Labels: minor
