Repository apollographql/space-kit, pull requests merged in 2021-02, with the labels that each got.

#308 fix(Modal): Fix repeating animations with custom components
  src/Modal/Modal.tsx
Labels: bug fix

#309 Tweak modal page background color
  src/Modal/Modal.tsx
Labels: minor

#311 Upgrade storybook to `^6.1.17`
  package-lock.json
  package.json
Labels: internal

#313 Add Odyssey icon
  src/icons/svgs/navigation/icon-odyssey.svg
Labels: minor, skip-release

#312 AR-2064 Resolve issue where `ListDivider` overflows container
  src/List/index.tsx
  src/ListDivider/index.tsx
Labels: bug fix

#310 [minor] Feature Intro Component
  src/FeatureIntro/index.ts
  src/FeatureIntroContent/index.tsx
  src/FeatureIntroControl/FeatureIntroControl.spec.tsx
  src/FeatureIntroControl/FeatureIntroControl.stories.mdx
  src/FeatureIntroControl/index.tsx
  src/FeatureIntroDismissButton/index.tsx
  src/FeatureIntroHeading/index.tsx
  src/FeatureIntroImage/index.tsx
  src/FeatureIntroLearnMoreLink/index.tsx
  src/FormControl/index.tsx
  src/shared/FeatureIntroControlContext/index.tsx
Labels: minor

#315 Pass `disabled` prop from options to downshift in `Select`
  src/Select/Select.story.mdx
  src/Select/index.tsx
Labels: bug fix

#316 FeatureIntro: add padding to increase click target
  src/FeatureIntroContent/index.tsx
  src/FeatureIntroControl/index.tsx
  src/FeatureIntroDismissButton/index.tsx
  src/FeatureIntroLearnMoreLink/index.tsx
Labels: skip-release

#314 Remove `publishishOnly` only script and run `build` in `prepare`
  package.json
Labels: skip-release

#321 add `FeatureIntro*` built folders to `.gitignore`
  .gitignore
Labels: internal

#320 AR-2118 add prestorybook script to build all svgs to tsx
  package.json
Labels: internal

#322 fix docs referencing non-existent `FormElement`
  src/FormControl/FormControls.stories.mdx
  src/TextField/TextField.tsx
Labels: bug fix

#319 Add missing icons (Person, Team, Error outline version)
  src/icons/svgs/essentials/icon-error.svg
  src/icons/svgs/essentials/icon-person.svg
  src/icons/svgs/essentials/icon-team.svg
Labels: minor
