Repository apollographql/space-kit, pull requests merged in 2021-03, with the labels that each got.

#324 AR-2127 fix `FormErrorMessage` not being removed when errors disappear
  src/FormControl/FormControl.spec.tsx
  src/FormErrorMessage/index.tsx
Labels: bug fix

#325 AR-2129 Allow all form control children to be removed on subsequent renders
  src/FormControl/FormControl.spec.tsx
  src/FormDescription/index.tsx
  src/FormEndAdornment/index.tsx
  src/FormHelperText/index.tsx
  src/FormLabel/index.tsx
  src/FormStartAdornment/index.tsx
Labels: bug fix

#327 AR-2135 Fix `Select` closing when interactive children receive focus
  src/Popover/index.tsx
  src/Select/index.tsx
Labels: bug fix

#328 Add guide for icon development
  src/icons/iconsGuide.stories.mdx
Labels: documentation

#329 remove debugging in Button test
  src/Button/Button.spec.tsx
Labels: internal, skip-release

#330 AR-2148 Fix repeated rendering of global styles for tooltip-like components
  src/AbstractTooltip/abstractTooltip/TippyStyles.tsx
  src/Popover/popover/TippyPopoverStyles.tsx
  src/Select/SelectTests.story.tsx
  src/SpaceKitProvider/index.tsx
  src/shared/components/SingletonComponent.spec.tsx
  src/shared/components/SingletonComponent.tsx
Labels: bug fix

#333 AR-2162 Add `as` prop to `Table` component
  src/Table/Table.spec.tsx
  src/Table/Table.tsx
Labels: minor

#326 Expose color prop for elect trigger
  src/Select/index.tsx
Labels: minor

#334 Pass maxWidth to Popover in Select
  src/Select/index.tsx
Labels: bug fix
