Repository apollographql/space-kit, pull requests merged in 2021-06, with the labels that each got.

#350 Backport of PR #340 update peer dependencies versions
  package.json
Labels: patch

#351 Enable versionBranches, document backport releases
  .autorc
  .circleci/config.yml
  CHANGELOG.md
Labels: patch

#353 Add solid time icon
  src/icons/iconsGuide.stories.mdx
  src/icons/svgs/solids/icon-time-solid.svg
Labels: minor

#352 Update themed components to respect theme from `SpaceKitProvider`
  src/AlertBanner/AlertBanner.tsx
  src/AlertCard/AlertCard.tsx
  src/Button/Button.stories.mdx
  src/Button/Button.tsx
  src/Button/button.stories/ButtonLayout.tsx
  src/Loaders/LoadingSpinner.tsx
  src/SpaceKitProvider/index.tsx
Labels: major

#356 Add icon for Sandbox
  src/icons/svgs/essentials/icon-sandbox.svg
Labels: minor

#357 Fix Popover component not being able to render >800 times without taking a dump on the main thread
  src/Popover/index.tsx
Labels: minor

#360 make alert card x optional
  src/AlertCard/AlertCard.story.mdx
  src/AlertCard/AlertCard.tsx
Labels: minor

#361 make dismissable optional:
  src/AlertCard/AlertCard.tsx
Labels: bug fix
